const PRODUCTS_DATA = [
  {
    id: "t1",
    title: "Featured Products",
    items: [
      {
        id: 47,
        name: "Casual Slim Fit Jacket",
        price: { whole: "39", fraction: "99" },
        sizes: ["S", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/g.1.jpg" }, { url: "jackets/g.2.jpg" }],
      },
      {
        id: 30,
        name: "Ripped Slim Tapered Jeans",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 5,
        img: [
          { url: "jeans/o.1.jpg" },
          { url: "jeans/o.2.jpg" },
          { url: "jeans/o.3.jpg" },
        ],
      },
      {
        id: 46,
        name: "Men's Denim Jacket",
        price: { whole: "44", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "jackets/f.1.jpg" }, { url: "jackets/f.2.jpg" }],
      },
      {
        id: 2,
        name: "Athletic T-Shirt",
        price: { whole: "9", fraction: "33" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [
          { url: "t-shirts/b.1.jpg" },
          { url: "t-shirts/b.2.jpg" },
          { url: "t-shirts/b.3.jpg" },
        ],
      },
      {
        id: 20,
        name: "Men's Slim Fit Jean",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/e.1.jpg" },
          { url: "jeans/e.2.jpg" },
          { url: "jeans/e.3.jpg" },
        ],
      },
      {
        id: 50,
        img: [{ url: "jackets/j.1.jpg" }, { url: "jackets/j.2.jpg" }],
        name: "Men's Rugged Dakota Jacket",
        price: { fraction: "99", whole: "59" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
      },
      {
        id: 70,
        img: [
          { url: "others/a.1.jpg" },
          { url: "others/a.2.jpg" },
          { url: "others/a.3.jpg" },
        ],
        name: "Athletic Jogger Pants",
        price: { fraction: "35", whole: "29" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
      },
      {
        id: 45,
        img: [
          { url: "jackets/e.1.jpg" },
          { url: "jackets/e.2.jpg" },
          { url: "jackets/e.3.jpg" },
        ],
        name: "Insulated Hooded Jacket",
        price: { fraction: "33", whole: "47" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
      },
      {
        id: 31,
        img: [
          { url: "hoodies/a.1.jpg" },
          { url: "hoodies/a.2.jpg" },
          { url: "hoodies/a.3.jpg" },
        ],
        name: "Champion Men's Hoodie",
        price: { fraction: "95", whole: "21" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
      },
    ],
  },
  {
    id: "t2",
    title: "Latest Trends",
    items: [
      {
        id: 52,
        name: "Levi' Sherpa Trucker Jacket",
        price: { whole: "57", fraction: "42" },
        sizes: ["M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/l.1.jpg" },
          { url: "jackets/l.2.jpg" },
          { url: "jackets/l.3.jpg" },
        ],
      },
      {
        id: 23,
        name: "Levi's Slim Straight Jean",
        price: { whole: "49", fraction: "99" },
        sizes: [28, 30, 32],
        rating: 4.5,
        img: [{ url: "jeans/h.1.jpg" }, { url: "jeans/h.2.jpg" }],
      },
      {
        id: 76,
        name: "Men's Floral Hawaiian Shirt",
        price: { whole: "22", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "others/h.1.jpg" }, { url: "others/h.2.jpg" }],
      },
      {
        id: 72,
        img: [{ url: "others/c.1.jpg" }, { url: "others/c.2.jpg" }],
        name: "Men's Active Jogger Pants",
        price: { fraction: "99", whole: "31" },
        rating: 5,
        sizes: ["S", "M", "L"],
      },
      {
        id: 32,
        img: [
          { url: "hoodies/b.1.jpg" },
          { url: "hoodies/b.2.jpg" },
          { url: "hoodies/b.3.jpg" },
        ],
        name: "Men's Athletic Hoodie",
        price: { fraction: "99", whole: "20" },
        rating: 5,
        sizes: ["S", "M", "L"],
      },
      {
        id: 20,
        name: "Men's Slim Fit Jean",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/e.1.jpg" },
          { url: "jeans/e.2.jpg" },
          { url: "jeans/e.3.jpg" },
        ],
      },
      {
        id: 44,
        name: "Lightweight Bomber Jacket",
        price: { whole: "35", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/d.1.jpg" }, { url: "jackets/d.2.jpg" }],
      },
      {
        id: 78,
        img: [
          { url: "others/g.1.jpg" },
          { url: "others/g.2.jpg" },
          { url: "others/g.3.jpg" },
        ],
        name: "Men's Perfect Fit Shorts",
        price: { fraction: "99", whole: "24" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
      },
      {
        id: 51,
        name: "Qulited Flanned Lined Jacket",
        price: { whole: "55", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/k.1.jpg" }, { url: "jackets/k.2.jpg" }],
      },
    ],
  },
];

export default PRODUCTS_DATA;
