const COLLECTION_DATA = {
  "t-shirts": {
    id: 1,
    title: "Casual T-Shirt",
    products: [
      {
        id: 1,
        name: "Men's Classic T-Shirt",
        price: { whole: "13", fraction: "99" },
        rating: 4,
        sizes: ["S", "M", "L"],
        img: [{ url: "t-shirts/a.1.jpg" }, { url: "t-shirts/a.2.jpg" }],
      },
      {
        id: 2,
        name: "Athletic T-Shirt",
        price: { whole: "9", fraction: "33" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [
          { url: "t-shirts/b.1.jpg" },
          { url: "t-shirts/b.2.jpg" },
          { url: "t-shirts/b.3.jpg" },
        ],
      },
      {
        id: 3,
        name: "Timberland Pro T",
        price: { whole: "20", fraction: "92" },
        rating: 4.5,
        sizes: ["S", "L", "XL"],
        img: [
          { url: "t-shirts/c.1.jpg" },
          { url: "t-shirts/c.2.jpg" },
          { url: "t-shirts/c.3.jpg" },
        ],
      },
      {
        id: 4,
        name: "Athletic Mens's T",
        price: { whole: "9", fraction: "93" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [
          { url: "t-shirts/d.1.jpg" },
          { url: "t-shirts/d.2.jpg" },
          { url: "t-shirts/d.3.jpg" },
        ],
      },
      {
        id: 5,
        name: "Crew Neck T-Shirt",
        price: { whole: "12", fraction: "66" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "t-shirts/e.1.jpg" }, { url: "t-shirts/e.2.jpg" }],
      },

      {
        id: 6,
        name: "Graphic Tee",
        price: { whole: "16", fraction: "18" },
        rating: 4,
        sizes: ["S", "M"],
        img: [
          { url: "t-shirts/f.1.jpg" },
          { url: "t-shirts/f.2.jpg" },
          { url: "t-shirts/f.3.jpg" },
        ],
      },
      {
        id: 7,
        name: "2-Pack Crewneck T",
        price: { whole: "13", fraction: "50" },
        rating: 4,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/g.1.jpg" }, { url: "t-shirts/g.2.jpg" }],
      },
      {
        id: 8,
        name: "Hanes Undershirt T",
        price: { whole: "16", fraction: "96" },
        rating: 4.5,
        sizes: ["M", "L", "XL"],
        img: [{ url: "t-shirts/h.1.jpg" }],
      },
      {
        id: 9,
        name: "Short Sleeve T",
        price: { whole: "16", fraction: "95" },
        rating: 4,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/i.jpg" }],
      },
      {
        id: 10,
        name: "Star Wars T-shirt",
        price: { whole: "15", fraction: "95" },
        rating: 5,
        sizes: ["S", "L", "XL"],
        img: [{ url: "t-shirts/j.1.jpg" }, { url: "t-shirts/j.2.jpg" }],
      },
      {
        id: 11,
        name: "Long Sleeve T-Shirt",
        price: { whole: "17", fraction: "99" },
        rating: 4,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/k.1.jpg" }],
      },
      {
        id: 12,
        name: "Nike Sportswear T shirt",
        price: { whole: "20", fraction: "04" },
        rating: 5,
        sizes: ["M", "XL"],
        img: [{ url: "t-shirts/l.1.jpg" }, { url: "t-shirts/l.2.jpg" }],
      },
      {
        id: 13,
        name: "3 Pack Military Tee",
        price: { whole: "14", fraction: "66" },
        rating: 4,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/m.1.jpg" }, { url: "t-shirts/m.2.jpg" }],
      },
      {
        id: 14,
        name: "Vans Classic T-Shirt",
        price: { whole: "19", fraction: "89" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/n.jpg" }],
      },
      {
        id: 15,
        name: "adidas Men's Tee",
        price: { whole: "15", fraction: "91" },
        rating: 4.5,
        sizes: ["S", "L", "XL"],
        img: [
          { url: "t-shirts/o.1.jpg" },
          { url: "t-shirts/o.2.jpg" },
          { url: "t-shirts/o.3.jpg" },
        ],
      },
    ],
  },

  jeans: {
    id: 2,
    title: "Premium Jeans",
    products: [
      {
        id: 16,
        name: "Straight Fit Jean",
        price: { whole: "31", fraction: "46" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/a.1.jpg" },
          { url: "jeans/a.2.jpg" },
          { url: "jeans/a.3.jpg" },
        ],
      },
      {
        id: 17,
        name: "Fit Flex Jean",
        price: { whole: "29", fraction: "99" },
        sizes: [28, 30, 32],
        rating: 4,
        img: [{ url: "jeans/b.1.jpg" }, { url: "jeans/b.2.jpg" }],
      },
      {
        id: 18,
        name: "Men's Athletic-Fit Jean",
        price: { whole: "32", fraction: "80" },
        sizes: [29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/c.1.jpg" },
          { url: "jeans/c.2.jpg" },
          { url: "jeans/c.3.jpg" },
        ],
      },
      {
        id: 19,
        name: "Tapered Leg Jean",
        price: { whole: "25", fraction: "62" },
        sizes: [28, 29, 30, 32],
        rating: 4,
        img: [{ url: "jeans/d.1.jpg" }, { url: "jeans/d.2.jpg" }],
      },
      {
        id: 20,
        name: "Men's Slim Fit Jean",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/e.1.jpg" },
          { url: "jeans/e.2.jpg" },
          { url: "jeans/e.3.jpg" },
        ],
      },

      {
        id: 21,
        name: "Relaxed Fit Stretch Jean",
        price: { whole: "33", fraction: "90" },
        sizes: [28, 29, 30],
        rating: 4,
        img: [{ url: "jeans/f.jpg" }],
      },
      {
        id: 22,
        name: "Regular Fit Bootcut Jean",
        price: { whole: "25", fraction: "98" },
        sizes: [29, 30, 32],
        rating: 5,
        img: [{ url: "jeans/g.1.jpg" }, { url: "jeans/g.2.jpg" }],
      },
      {
        id: 23,
        name: "Levi's Slim Straight Jean",
        price: { whole: "49", fraction: "99" },
        sizes: [28, 30, 32],
        rating: 4.5,
        img: [{ url: "jeans/h.1.jpg" }, { url: "jeans/h.2.jpg" }],
      },
      {
        id: 24,
        name: "Wrancher Dress Jean",
        price: { whole: "24", fraction: "29" },
        sizes: [28, 30, 32],
        rating: 4,
        img: [{ url: "jeans/i.1.jpg" }, { url: "jeans/i.2.jpg" }],
      },
      {
        id: 25,
        name: "Men's Slim-Fit Jean",
        price: { whole: "27", fraction: "67" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [{ url: "jeans/j.1.jpg" }, { url: "jeans/j.2.jpg" }],
      },
      {
        id: 26,
        name: "Men's Straight Fit Jeans",
        price: { whole: "27", fraction: "89" },
        sizes: [28, 32],
        rating: 5,
        img: [{ url: "jeans/k.1.jpg" }, { url: "jeans/k.2.jpg" }],
      },
      {
        id: 27,
        name: "All Seasons Tech Pants",
        price: { whole: "36", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 4,
        img: [{ url: "jeans/l.1.jpg" }, { url: "jeans/l.2.jpg" }],
      },
      {
        id: 28,
        name: "Men's Skinny fit Jean",
        price: { whole: "32", fraction: "20" },
        sizes: [28, 29, 30, 32],
        rating: 5,
        img: [
          { url: "jeans/m.1.jpg" },
          { url: "jeans/m.2.jpg" },
          { url: "jeans/m.3.jpg" },
        ],
      },
      {
        id: 29,
        name: "Straight Fit Denim Jean",
        price: { whole: "29", fraction: "77" },
        sizes: [28, 30],
        rating: 4,
        img: [{ url: "jeans/n.jpg" }],
      },
      {
        id: 30,
        name: "Ripped Slim Tapered Jeans",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 5,
        img: [
          { url: "jeans/o.1.jpg" },
          { url: "jeans/o.2.jpg" },
          { url: "jeans/o.3.jpg" },
        ],
      },
    ],
  },

  hoodies: {
    id: 3,
    title: "Trendy Hoodies",
    products: [
      {
        id: 31,
        name: "Champion Men's Hoodie",
        price: { whole: "21", fraction: "95" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [
          { url: "hoodies/a.1.jpg" },
          { url: "hoodies/a.2.jpg" },
          { url: "hoodies/a.3.jpg" },
        ],
      },
      {
        id: 32,
        name: "Men's Athletic Hoodie",
        price: { whole: "20", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [
          { url: "hoodies/b.1.jpg" },
          { url: "hoodies/b.2.jpg" },
          { url: "hoodies/b.3.jpg" },
        ],
      },

      {
        id: 33,
        name: "Hanes Men's Hooded Sweatshirt",
        price: { whole: "24", fraction: "33" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/c.1.jpg" }, { url: "hoodies/c.2.jpg" }],
      },
      {
        id: 34,
        name: "Champion Men's Pullover Hoodie",
        price: { whole: "31", fraction: "99" },
        sizes: ["M", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/d.1.jpg" }, { url: "hoodies/d.2.jpg" }],
      },
      {
        id: 35,
        name: "Hanes Men's Heavyweight Hoodie",
        price: { whole: "34", fraction: "20" },
        sizes: ["S", "L", "XL"],
        rating: 4.5,
        img: [
          { url: "hoodies/e.1.jpg" },
          { url: "hoodies/e.2.jpg" },
          { url: "hoodies/e.3.jpg" },
        ],
      },

      {
        id: 36,
        name: "Champion Men's Authentic Hoodie",
        price: { whole: "45", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "hoodies/f.1.jpg" }, { url: "hoodies/f.2.jpg" }],
      },
      {
        id: 37,
        name: "Men's Athletic Hoodie",
        price: { whole: "23", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [
          { url: "hoodies/g.1.jpg" },
          { url: "hoodies/g.2.jpg" },
          { url: "hoodies/g.3.jpg" },
        ],
      },
      {
        id: 38,
        name: "Under Armour Hoodie",
        price: { whole: "37", fraction: "95" },
        sizes: ["S", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/h.1.jpg" }],
      },

      {
        id: 39,
        name: "Hanes Men's Smart Hoodie",
        price: { whole: "44", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "hoodies/i.1.jpg" }, { url: "hoodies/i.2.jpg" }],
      },
      {
        id: 40,
        name: "adidas Men's Hoodie",
        price: { whole: "44", fraction: "35" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "hoodies/j.1.jpg" }, { url: "hoodies/j.2.jpg" }],
      },
    ],
  },

  jackets: {
    id: 4,
    title: "Branded Jackets",
    products: [
      {
        id: 41,
        name: "Casual Bomber Jacket",
        price: { whole: "33", fraction: "99" },
        sizes: ["S", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/a.1.jpg" },
          { url: "jackets/a.2.jpg" },
          { url: "jackets/a.3.jpg" },
        ],
      },
      {
        id: 42,
        name: "Levi's Military Jacket",
        price: { whole: "45", fraction: "25" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/b.1.jpg" },
          { url: "jackets/b.2.jpg" },
          { url: "jackets/b.3.jpg" },
        ],
      },
      {
        id: 43,
        name: "Shirt Jacket with Hood",
        price: { whole: "29", fraction: "99" },
        sizes: ["M", "L"],
        rating: 4.5,
        img: [{ url: "jackets/c.1.jpg" }, { url: "jackets/c.2.jpg" }],
      },
      {
        id: 44,
        name: "Lightweight Bomber Jacket",
        price: { whole: "35", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "jackets/d.1.jpg" }, { url: "jackets/d.2.jpg" }],
      },
      {
        id: 45,
        name: "Insulated Hooded Jacket",
        price: { whole: "47", fraction: "33" },
        sizes: ["S", "M", "L"],
        rating: 4.5,
        img: [
          { url: "jackets/e.1.jpg" },
          { url: "jackets/e.2.jpg" },
          { url: "jackets/e.3.jpg" },
        ],
      },
      {
        id: 46,
        name: "Men's Denim Jacket",
        price: { whole: "44", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "jackets/f.1.jpg" }, { url: "jackets/f.2.jpg" }],
      },
      {
        id: 47,
        name: "Casual Slim Fit Jacket",
        price: { whole: "39", fraction: "99" },
        sizes: ["S", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/g.1.jpg" }, { url: "jackets/g.2.jpg" }],
      },
      {
        id: 48,
        name: "Military Hooded Jacket",
        price: { whole: "49", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "jackets/h.1.jpg" }, { url: "jackets/h.2.jpg" }],
      },
      {
        id: 49,
        name: "Nylon Jacket",
        price: { whole: "32", fraction: "04" },
        sizes: ["S", "XL"],
        rating: 4,
        img: [{ url: "jackets/i.jpg" }],
      },
      {
        id: 50,
        name: "Men's Rugged Dakota Jacket",
        price: { whole: "59", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "jackets/j.1.jpg" }, { url: "jackets/j.2.jpg" }],
      },
      {
        id: 51,
        name: "Qulited Flanned Lined Jacket",
        price: { whole: "55", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/k.1.jpg" }, { url: "jackets/k.2.jpg" }],
      },
      {
        id: 52,
        name: "Levi' Sherpa Trucker Jacket",
        price: { whole: "57", fraction: "42" },
        sizes: ["M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/l.1.jpg" },
          { url: "jackets/l.2.jpg" },
          { url: "jackets/l.3.jpg" },
        ],
      },
      {
        id: 53,
        name: "Levi's Men's Denim",
        price: { whole: "54", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "jackets/m.jpg" }],
      },
      {
        id: 54,
        name: "Duck Men's Jacket",
        price: { whole: "65", fraction: "38" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "jackets/n.jpg" }],
      },
    ],
  },
  shoes: {
    id: 5,
    title: "Sporty Shoes",
    products: [
      {
        id: 55,
        name: "Nike Revolution 5",
        price: { whole: "51", fraction: "98" },
        rating: 4,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/b.1.jpg" }, { url: "shoes/b.2.jpg" }],
      },
      {
        id: 56,
        name: "Rebook Hi2 Sneaker",
        price: { whole: "44", fraction: "94" },
        rating: 4.5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/c.1.jpg" }, { url: "shoes/c.2.jpg" }],
      },
      {
        id: 57,
        name: "Vans Low-Top Sneakers",
        price: { whole: "49", fraction: "41" },
        rating: 4.5,
        sizes: ["8", "9", "10"],
        img: [
          { url: "shoes/d.1.jpg" },
          { url: "shoes/d.2.jpg" },
          { url: "shoes/d.3.jpg" },
        ],
      },
      {
        id: 58,
        name: "Under Armour Shoes",
        price: { whole: "56", fraction: "00" },
        rating: 4,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/e.1.jpg" }, { url: "shoes/e.2.jpg" }],
      },

      {
        id: 59,
        name: "Timberland Pro Powertrain",
        price: { whole: "89", fraction: "93" },
        rating: 4,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/f.jpg" }],
      },
      {
        id: 60,
        name: "adidas 3.O Skate Shoe",
        price: { whole: "53", fraction: "50" },
        rating: 4.5,
        sizes: ["7", "8", "9", "10"],
        img: [
          { url: "shoes/g.1.jpg" },
          { url: "shoes/g.2.jpg" },
          { url: "shoes/g.3.jpg" },
        ],
      },
      {
        id: 61,
        name: "Puma Tazon Shoe",
        price: { whole: "61", fraction: "74" },
        rating: 4.5,
        sizes: ["7", "8"],
        img: [
          { url: "shoes/h.1.jpg" },
          { url: "shoes/h.2.jpg" },
          { url: "shoes/h.3.jpg" },
        ],
      },
      {
        id: 62,
        name: "Fila Vulc 13",
        price: { whole: "54", fraction: "99" },
        rating: 4.5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/i.jpg" }],
      },
      {
        id: 63,
        name: "Reebok Leather Sneaker",
        price: { whole: "67", fraction: "38" },
        rating: 5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/j.1.jpg" }, { url: "shoes/j.2.jpg" }],
      },
      {
        id: 64,
        name: "Reebok Club C Sneaker",
        price: { whole: "69", fraction: "99" },
        rating: 4.5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/k.jpg" }],
      },
      {
        id: 65,
        name: "Under Armour Tr 3",
        price: { whole: "59", fraction: "05" },
        rating: 5,
        sizes: ["7", "8", "9", "10"],
        img: [
          { url: "shoes/l.1.jpg" },
          { url: "shoes/l.2.jpg" },
          { url: "shoes/l.3.jpg" },
        ],
      },
      {
        id: 66,
        name: "Nike Basketball Shoes",
        price: { whole: "109", fraction: "27" },
        rating: 5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/m.1.jpg" }, { url: "shoes/m.2.jpg" }],
      },
      {
        id: 67,
        name: "Men's Wrenford Sneaker",
        price: { whole: "58", fraction: "95" },
        rating: 4.5,
        sizes: ["7", "8", "9", "10"],
        img: [{ url: "shoes/n.jpg" }],
      },
      {
        id: 68,
        name: "Nike KD Trey 5",
        price: { whole: "76", fraction: "91" },
        rating: 5,
        sizes: ["7", "8", "9", "10"],
        img: [
          { url: "shoes/o.1.jpg" },
          { url: "shoes/o.2.jpg" },
          { url: "shoes/o.3.jpg" },
        ],
      },
      {
        id: 69,
        name: "adidas Court Tennis Shoes",
        price: { whole: "50", fraction: "00" },
        rating: 4.5,
        sizes: ["7", "8", "9"],
        img: [{ url: "shoes/a.1.jpg" }, { url: "shoes/a.2.jpg" }],
      },
    ],
  },

  "active-wear": {
    id: 7,
    title: "Men's Active-wear",
    products: [
      {
        id: 71,
        name: "Men's Sleeveless T-shirt",
        price: { whole: "24", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "others/b.1.jpg" }, { url: "others/b.2.jpg" }],
      },
      {
        id: 70,
        name: "Athletic Jogger Pants",
        price: { whole: "29", fraction: "35" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [
          { url: "others/a.1.jpg" },
          { url: "others/a.2.jpg" },
          { url: "others/a.3.jpg" },
        ],
      },
      {
        id: 2,
        name: "Athletic T-Shirt",
        price: { whole: "9", fraction: "33" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [
          { url: "t-shirts/b.1.jpg" },
          { url: "t-shirts/b.2.jpg" },
          { url: "t-shirts/b.3.jpg" },
        ],
      },
      {
        id: 32,
        name: "Men's Athletic Hoodie",
        price: { whole: "20", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [
          { url: "hoodies/b.1.jpg" },
          { url: "hoodies/b.2.jpg" },
          { url: "hoodies/b.3.jpg" },
        ],
      },
      {
        id: 72,
        name: "Men's Active Jogger Pants",
        price: { whole: "31", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "others/c.1.jpg" }, { url: "others/c.2.jpg" }],
      },
      {
        id: 73,
        name: "Under Armour Shorts",
        price: { whole: "60", fraction: "05" },
        rating: 4.5,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "others/d.1.jpg" }, { url: "others/d.2.jpg" }],
      },
      {
        id: 74,
        name: "Champion Men's Shorts",
        price: { whole: "26", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "others/e.1.jpg" }, { url: "others/e.2.jpg" }],
      },
      {
        id: 75,
        name: "Men's 2 Pack Shorts",
        price: { whole: "31", fraction: "99" },
        rating: 4.5,
        sizes: ["M", "L", "XL"],
        img: [{ url: "others/f.1.jpg" }, { url: "others/f.2.jpg" }],
      },
      {
        id: 37,
        name: "Men's Athletic Hoodie",
        price: { whole: "23", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [
          { url: "hoodies/g.1.jpg" },
          { url: "hoodies/g.2.jpg" },
          { url: "hoodies/g.3.jpg" },
        ],
      },
      {
        id: 4,
        name: "Athletic Mens's T",
        price: { whole: "9", fraction: "93" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [
          { url: "t-shirts/d.1.jpg" },
          { url: "t-shirts/d.2.jpg" },
          { url: "t-shirts/d.3.jpg" },
        ],
      },
    ],
  },

  
  "winter-collection": {
    id: 8,
    title: "Winter Collection",
    products: [
      {
        id: 52,
        name: "Levi' Sherpa Trucker Jacket",
        price: { whole: "57", fraction: "42" },
        sizes: ["M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/l.1.jpg" },
          { url: "jackets/l.2.jpg" },
          { url: "jackets/l.3.jpg" },
        ],
      },
      {
        id: 31,
        name: "Champion Men's Hoodie",
        price: { whole: "21", fraction: "95" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "hoodies/a.1.jpg" }, { url: "hoodies/a.2.jpg" }, { url: "hoodies/a.3.jpg" }],
      },
      {
        id: 41,
        name: "Casual Bomber Jacket",
        price: { whole: "33", fraction: "99" },
        sizes: ["S", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/a.1.jpg" },
          { url: "jackets/a.2.jpg" },
          { url: "jackets/a.3.jpg" },
        ],
      },
    
      {
        id: 43,
        name: "Shirt Jacket with Hood",
        price: { whole: "29", fraction: "99" },
        sizes: ["M", "L"],
        rating: 4.5,
        img: [{ url: "jackets/c.1.jpg" }, { url: "jackets/c.2.jpg" }],
      },
      {
        id: 44,
        name: "Lightweight Bomber Jacket",
        price: { whole: "35", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "jackets/d.1.jpg" }, { url: "jackets/d.2.jpg" }],
      },
   
      {
        id: 32,
        name: "Men's Athletic Hoodie",
        price: { whole: "20", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "hoodies/b.1.jpg" }, { url: "hoodies/b.2.jpg" }, { url: "hoodies/b.3.jpg" }],
      },
      {
        id: 33,
        name: "Hanes Men's Hooded Sweatshirt",
        price: { whole: "24", fraction: "33" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/c.1.jpg" },{ url: "hoodies/c.2.jpg" }],
      },
      {
        id: 51,
        name: "Qulited Flanned Lined Jacket",
        price: { whole: "55", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [{ url: "jackets/k.1.jpg" }, { url: "jackets/k.2.jpg" }],
      },
      {
        id: 34,
        name: "Champion Men's Pullover Hoodie",
        price: { whole: "31", fraction: "99" },
        sizes: [ "M", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/d.1.jpg" }, { url: "hoodies/d.2.jpg" }],
      },
      {
        id: 35,
        name: "Hanes Men's Heavyweight Hoodie",
        price: { whole: "34", fraction: "20" },
        sizes: ["S", "L", "XL"],
        rating: 4.5,
        img: [{ url: "hoodies/e.1.jpg" }, { url: "hoodies/e.2.jpg" }, { url: "hoodies/e.3.jpg" }],
      },
      {
        id: 50,
        name: "Men's Rugged Dakota Jacket",
        price: { whole: "59", fraction: "99" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "jackets/j.1.jpg" }, { url: "jackets/j.2.jpg" }],
      },
      {
        id: 36,
        name: "Champion Men's Authentic Hoodie",
        price: { whole: "45", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [{ url: "hoodies/f.1.jpg" },{ url: "hoodies/f.2.jpg" }],
      },
      {
        id: 42,
        name: "Levi's Military Jacket",
        price: { whole: "45", fraction: "25" },
        sizes: ["S", "M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/b.1.jpg" },
          { url: "jackets/b.2.jpg" },
          { url: "jackets/b.3.jpg" },
        ],
      },
      {
        id: 37,
        name: "Men's Athletic Hoodie",
        price: { whole: "23", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "hoodies/g.1.jpg" }, { url: "hoodies/g.2.jpg" }, { url: "hoodies/g.3.jpg" }],
      },
      {
        id: 38,
        name: "Under Armour Hoodie",
        price: { whole: "37", fraction: "95" },
        sizes: ["S", "L", "XL"],
        rating: 4,
        img: [{ url: "hoodies/h.1.jpg" }],
      },
    ],
  },

  "summer-collection": {
    id: 9,
    title: "Summer Collection",
    products: [
      {
        id: 76,
        name: "Men's Floral Hawaiian Shirt",
        price: { whole: "22", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "others/h.1.jpg" }, { url: "others/h.2.jpg" }],
      },
      {
        id: 15,
        name: "adidas Men's Tee",
        price: { whole: "15", fraction: "91" },
        rating: 4.5,
        sizes: ["S", "L", "XL"],
        img: [
          { url: "t-shirts/o.1.jpg" },
          { url: "t-shirts/o.2.jpg" },
          { url: "t-shirts/o.3.jpg" },
        ],
      },

      {
        id: 76,
        name: "Men's Perfect Fit Shorts",
        price: { whole: "24", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [
          { url: "others/g.1.jpg" },
          { url: "others/g.2.jpg" },
          { url: "others/g.3.jpg" },
        ],
      },

      {
        id: 77,
        name: "Men's Short Sleeves Shirt",
        price: { whole: "21", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [
          { url: "others/i.1.jpg" },
          { url: "others/i.2.jpg" },
          { url: "others/i.3.jpg" },
        ],
      },
      {
        id: 7,
        name: "2-Pack Crewneck T",
        price: { whole: "13", fraction: "50" },
        rating: 4,
        sizes: ["S", "M", "L", "XL"],
        img: [{ url: "t-shirts/g.1.jpg" }, { url: "t-shirts/g.2.jpg" }],
      },
      {
        id: 6,
        name: "Graphic Tee",
        price: { whole: "16", fraction: "18" },
        rating: 4,
        sizes: ["S", "M"],
        img: [
          { url: "t-shirts/f.1.jpg" },
          { url: "t-shirts/f.2.jpg" },
          { url: "t-shirts/f.3.jpg" },
        ],
      },
      {
        id: 74,
        name: "Champion Men's Shorts",
        price: { whole: "26", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "others/e.1.jpg" }, { url: "others/e.2.jpg" }],
      },

      {
        id: 75,
        name: "Men's 2 Pack Shorts",
        price: { whole: "31", fraction: "99" },
        rating: 4.5,
        sizes: ["M", "L", "XL"],
        img: [{ url: "others/f.1.jpg" }, { url: "others/f.2.jpg" }],
      },
      {
        id: 5,
        name: "Crew Neck T-Shirt",
        price: { whole: "12", fraction: "66" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "t-shirts/e.1.jpg" }, { url: "t-shirts/e.2.jpg" }],
      },
      {
        id: 72,
        name: "Men's Active Jogger Pants",
        price: { whole: "31", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "others/c.1.jpg" }, { url: "others/c.2.jpg" }],
      },
    ],
  },
  
  "top-deals": {
    id: 10,
    title: "Top Deals",
    products: [
      {
        id: 52,
        name: "Levi' Sherpa Trucker Jacket",
        price: { whole: "57", fraction: "42" },
        sizes: ["M", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/l.1.jpg" },
          { url: "jackets/l.2.jpg" },
          { url: "jackets/l.3.jpg" },
        ],
      },
      {
        id: 30,
        name: "Ripped Slim Tapered Jeans",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 5,
        img: [
          { url: "jeans/o.1.jpg" },
          { url: "jeans/o.2.jpg" },
          { url: "jeans/o.3.jpg" },
        ],
      },
      {
        id: 76,
        name: "Men's Floral Hawaiian Shirt",
        price: { whole: "22", fraction: "99" },
        rating: 4.5,
        sizes: ["S", "M", "L"],
        img: [{ url: "others/h.1.jpg" }, { url: "others/h.2.jpg" }],
      },
      {
        id: 15,
        name: "adidas Men's Tee",
        price: { whole: "15", fraction: "91" },
        rating: 4.5,
        sizes: ["S", "L", "XL"],
        img: [
          { url: "t-shirts/o.1.jpg" },
          { url: "t-shirts/o.2.jpg" },
          { url: "t-shirts/o.3.jpg" },
        ],
      },
      {
        id: 31,
        name: "Champion Men's Hoodie",
        price: { whole: "21", fraction: "95" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        img: [
          { url: "hoodies/a.1.jpg" },
          { url: "hoodies/a.2.jpg" },
          { url: "hoodies/a.3.jpg" },
        ],
      },
      {
        id: 72,
        name: "Men's Active Jogger Pants",
        price: { whole: "31", fraction: "99" },
        sizes: ["S", "M", "L"],
        rating: 5,
        img: [{ url: "others/c.1.jpg" }, { url: "others/c.2.jpg" }],
      },
      {
        id: 46,
        name: "Men's Denim Jacket",
        price: { whole: "44", fraction: "00" },
        sizes: ["S", "M", "L", "XL"],
        rating: 4,
        img: [{ url: "jackets/f.1.jpg" }, { url: "jackets/f.2.jpg" }],
      },
      {
        id: 20,
        name: "Men's Slim Fit Jean",
        price: { whole: "24", fraction: "99" },
        sizes: [28, 29, 30, 32],
        rating: 4.5,
        img: [
          { url: "jeans/e.1.jpg" },
          { url: "jeans/e.2.jpg" },
          { url: "jeans/e.3.jpg" },
        ],
      },
      {
        id: 41,
        name: "Casual Bomber Jacket",
        price: { whole: "33", fraction: "99" },
        sizes: ["S", "L", "XL"],
        rating: 5,
        img: [
          { url: "jackets/a.1.jpg" },
          { url: "jackets/a.2.jpg" },
          { url: "jackets/a.3.jpg" },
        ],
      },
 
      {
        id: 26,
        name: "Men's Straight Fit Jeans",
        price: { whole: "27", fraction: "89" },
        sizes: [28, 32],
        rating: 5,
        img: [{ url: "jeans/k.1.jpg" }, { url: "jeans/k.2.jpg" }],
      },
      
    ],
  },
};

export default COLLECTION_DATA;
